language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t 239002210/web-speed-app -f Dockerfile.dev .

before_script:
  - docker run 239002210/web-speed-app npm run stylelint:fix

script:
  - docker run -e CI=true 239002210/web-speed-app npm run test -- -u

after_success:
  - echo "Unit tests success"