language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t 239002210/web-speed-app -f Dockerfile.dev .

before_script:
    - docker run 239002210/web-speed-app npm run stylelint:fix
  
script:
    - docker run -e CI=true 239002210/web-speed-app npm run test -- -u
  
after_success:
    - echo "Unit tests success"

before_deploy:
    - docker run 239002210/web-speed-app npm run build

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  target_branch: gh-pages
  keep_history: true
  on:
    branch: master